<?php

namespace Database\Seeders;

use App\Models\Commune;
use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CommuneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            // Kampong Thom
            'Baray' => [
                'Kongsamrithoudom',
                'Ballangk',
                'Baray',
                'Boeng',
                'Chaeung Daeung',
                'Chraneang ',
                'Chhuk Khsach',
                'Chong Doung',
                'Chrolong',
                'Kokir Thum',
                'Krava',
                'Andoung Pou',
                'Pongro',
                'Sou Young',
                'Sralau',
                'Svay Phleung',
                'Tnaot Chum',
                'Triel',
            ],
            'Kampong Svay' => [
                'Chey',
                'Damrei Slab',
                'Kampong Kou',
                'Kampong Svay',
                'Nipech',
                'Phat Sanday',
                'San Kor',
                'Tbaeng',
                'Trapeang Ruessei',
                'Kdei Doung',
                'Prey Kuy',
            ],
            'Stueng Saen' => [
                'Damrei Choan Khla',
                'Kampong Roteh',
                'Ou Kanthor',
                'Kampong Krabau',
                'Prey Ta Hu',
                'Achar Leak',
                'Srayov',
            ],
            'Prasat Balang' => [
                'Doung',
                'Kraya',
                'Phan Nheum',
                'Sakream',
                'Sala Visai',
                'Sameakki',
                'Tuol Kreul',
            ],
            'Prasat Sambour' => [
                'Chhuk',
                'Koul',
                'Sambour',
                'Sraeung',
                'Tang Krasau',
            ],
            'Sandan' => [
                'Chheu Teal',
                'Dang Kambet',
                'Klaeng',
                'Mean Rith',
                'Mean Chey',
                'Ngan',
                'Sandan',
                'Sochet',
                'Tum Ring',
            ],
            'Santuk' => [
                'Boeng Lvea',
                'Chroab',
                'Kampong Thmar',
                'Kakaoh',
                'Kraya',
                'Pnov',
                'Prasat',
                'Tang Krasang',
                'Ti Pou',
                'Tboung Krapeu',
            ],
            'Stoung' => [
                'Banteay Stoung',
                'Chamna Kraom',
                'Chamna Leu',
                'Kampong Chen Cheung',
                'Kampong Chen Tbong',
                'Msa Krang',
                'Peam Bang',
                'Por Pok',
                'Pralay',
                'Preah Damrei',
                'Rung Roeang',
                'Samprouch',
                'Trea',
            ],
            'Taing Kok' => [
                'Souyoung',
                'Chraneang',
                'Chrolong',
                'Andong Pou',
                'Pongro',
                'Sralau',
                'Svay Phleung',
                'Triel ',
            ],

            // Banteay Meanchey
            'Mongkol Borey' => [
                'Banteay Neang',
                'Bat Trang',
                'Chamnaom',
                'Kouk Ballangk',
                'Koy Maeng',
                'Ou Prasat',
                'Phnum Touch',
                'Rohat Tuek',
                'Ruessei Kraok',
                'Sambuor',
                'Soea',
                'Srah Reang',
                'Ta Lam',
            ],
            'Phnom Srok' => [
                'Nam Tau',
                'Paoy Char',
                'Ponley',
                'Spean Sraeng',
                'Srah Chik',
                'Phnum Dei',
            ],
            'Preah Neth Preah' => [
                'Chhnuor Mean Chey',
                'Chob Veari',
                'Phnum Lieb',
                'Prasat',
                'Preah Netr Preah',
                'Rohal',
                'Tean Kam',
                'Tuek Chour',
            ],
            'Ou Chrov' => [
                'Changha',
                'Koub',
                'Kuttasat',
                'Nimitt',
                'Samraong',
                'Souphi',
                'Soengh',
                'Paoy Paet',
                'Ou Bei Choan',
            ],
            'Serei Saophoan' => [
                'Bos Sbov',
                'Kampong Svay',
                'Kaoh Pong Satv',
                'Mkak',
                'Ou Ambel',
                'Phniet',
                'Preah Ponlea',
                'Tuek Thla',
            ],
            'Thmar Puok' => [
                'Banteay Chhmar',
                'Kouk Romiet',
                'Thmar Puok',
                'Kouk Kakthen',
                'Kumru',
                'Phum Thmei',
            ],
            'Svay Chek' => [
                'Phkoam',
                'Sarongk',
                'Sla Kram',
                'Svay Chek',
                'Ta Baen',
                'Ta Phou',
                'Treas',
                'Roluos',
            ],
            'Malai' => [
                'Boeng Beng',
                'Malai',
                'Ou Sampor',
                'Ou Sralau',
                'Tuol Pongro',
                'Ta Kong',
            ],
            'Poipet' => [
                'Ou Chrov',
                'Russey Keo',
            ],

            // Battam bong
            'Banan' => [
                'Kantueu Muoy',
                'Kantueu Pir',
                'Bay Damram',
                'Chheu Teal',
                'Chaeng Mean Chey',
                'Phnum Sampov',
                'Snoeng',
                'Ta Kream',
            ],
            'Thma Koul' => [
                'Ta Pung',
                'Ta Meun',
                'Ou Ta Ki',
                'Chrey',
                'Anlong Run',
                'Chrouy Sdau',
                'Boeng Pring',
                'Kouk Khmum',
                'Bansay Traeng',
                'Rung Chrey',
            ],
            'Bat Dambang' => [
                'Tuol Ta Aek',
                'Preaek Preah Sdach',
                'Rotanak',
                'Chamkar Samraong',
                'Sla Kaet',
                'Kdol Doun Teav',
                'Ou Mal',
                'Voat Kor',
                'Ou Char',
                'Svay Pao',
            ],
            'Bavel' => [
                'Bavel',
                'Khnach Romeas',
                'Lvea',
                'Prey Khpus',
                'Ompil Pram Doem',
                'Kdok Ta Hen',
                'Khlaeng Meas',
                'Boeng Pram',
            ],
            'Aek Phnum' => [
                'Preaek Norint',
                'Samraong Knong',
                'Preaek Khpob',
                'Preaek Luong',
                'Peam Aek',
                'Prey Chas',
                'Kaoh Chiveang',
            ],
            'Moung Ruessei' => [
                'Moung',
                'Kear',
                'Prey Svay',
                'Ruessei Krang',
                'Chrey',
                'Ta Loas',
                'Kakaoh',
                'Prey Touch',
                'Robas Mongkol',
            ],
            'Rotanak Mondol' => [
                'Sdau',
                'Andaeuk Haeb',
                'Phlov Meas',
                'Traeng',
                'Reaksmei Songha',
            ],
            'Sangkae' => [
                'Anlong Vil',
                'Norea',
                'Ta Pon',
                'Roka',
                'Kampong Preah',
                'Kampong Prieng',
                'Reang Kesei',
                'Ou Dambang Muoy',
                'Ou Dambang Pir',
                'Vaot Ta Muem',
            ],
            'Samlout' => [
                'Ta Taok',
                'Kampong Lpou',
                'Ou Samrel',
                'Sung',
                'Samlout',
                'Mean Chey',
                'Ta Sanh',
            ],
            'Sampov Lun' => [
                'Sampov Lun',
                'Angkor Ban',
                'Ta Sda',
                'Santepheap',
                'Serei Mean Chey',
                'Chrey Seima',
            ],
            'Phnum Proek' => [
                'Phnum Proek',
                'Pech Chenda',
                'Bour',
                'Barang Thleak',
                'Ou Rumduol',
            ],
            'Kamrieng' => [
                'Kamrieng',
                'Boeng Reang',
                'Ou Da',
                'Trang',
                'Ta Saen',
                'Ta Krai',
            ],
            'Koas Krala' => [
                'Thipakdei',
                'Koh Kralor',
                'Hab',
                'Preah Phos',
                'Doun Ba',
                'Chhnal Moan',
            ],
            'Rukhakiri' => [
                'Prek Chik',
                'Prey Tra Larch',
                'Muk Reah',
                'Stok Bravik',
                'Basak',
            ],

            // Kampong Cham
            'Batheay' => [
                'Batheay',
                'Chbar Ampov',
                'Chealea',
                'Cheung Prey',
                'Me Pring',
                "Ph'av",
                'Sambour',
                'Sandaek',
                'Tang Krang',
                'Tang Krasang',
                'Trab',
                'Tumnob',
            ],
            'Chamkar Leu' => [
                'Bos Khnor',
                'Chamkar Andoung',
                'Cheyyou',
                'Lvea Leu',
                'Spueu',
                'Svay Teab',
                'Ta Ong',
                'Ta Prok',
            ],
            'Cheung Prey' => [
                'Khnor Dambang',
                'Kouk Rovieng',
                'Pdau Chum',
                'Prey Char',
                'Pring Chrum',
                'Sampong Chey',
                'Sdaeung Chey',
                'Soutib',
                'Sramar',
                'Trapeang Kor',
            ],
            'Kampong Cham' => [
                'Boeng Kok',
                'Kampong Cham',
                'Sambor Meas',
                'Veal Vong',
            ],
            'Kampong Siem' => [
                'Ampil',
                'Hanchey',
                'Kien Chrey',
                'Kokor',
                'Kaoh Mitt',
                'Kaoh Roka',
                'Kaoh Samraong',
                'Kaoh Tontuem',
                'Krala',
                'Ou Svay',
                "Ro'ang",
                'Rumchek',
                'Srak',
                'Trean',
                'Vihear Thum',
            ],
            'Kang Meas' => [
                'Angkor Ban',
                'Kang Ta Noeng',
                'Khchau',
                'Peam Chi Kang',
                'Preaek Koy',
                'Preaek Krabau',
                'Reay Pay',
                'Roka ar',
                'Roka Koy',
                'Sdau',
                'Sour Kong',
            ],
            'Kaoh Soutin' => [
                'Kampong Reab',
                'Kaoh Sotin',
                'Lve',
                'Moha Leaph',
                'Moha Khnhoung',
                'Peam Prathnuoh',
                'Pongro',
                'Preaek Ta Nong',
            ],
            'Prey Chhor' => [
                'Baray',
                'Boeng Nay',
                'Chrey Vien',
                'Khvet Thum',
                'Kor',
                'Krouch',
                'Lvea',
                'Mien',
                'Prey Chhor',
                'Sour Saen',
                'Samraong',
                'Sragnae',
                'Thma Pun',
                'Tong Rong',
                'Trapeang Preah',
            ],
            'Srey Santhor' => [
                'Baray',
                'Chi Bal',
                'Khnar Sa',
                'Kaoh Andaet',
                'Mean Chey',
                'Pteah Kandal',
                'Pram Yam',
                'Preaek Dambouk',
                'Preaek Pou',
                'Preaek Rumdeng',
                'Ruessei Srok',
                'Svay Pou',
                'Svay Sach Phnum',
                'Tong Tralach',
            ],
            'Stueng Trang' => [
                'Areaks Tnaot',
                'Dang Kdar',
                'Khpob Ta Nguon',
                'Me Sar Chrey',
                'Ou Mlu',
                'Peam Kaoh Sna',
                'Preah Andoung',
                'Preaek Bak',
                'Preaek Kak',
                'Soupheas',
                'Tuol Preah Khleang',
                'Tuol Sambuor',
            ],

            // Kampong Chnang
            'Baribour' => [
                'Anhchanh Rung',
                'Chhnok Tru',
                'Chak',
                'Khon Rang',
                'Kampong Preah Kokir',
                'Melum',
                'Phsar',
                'Pech Changvar',
                'Popel',
                'Ponley',
                'Trapeang Chan',
            ],
            'Chol Kiri' => [
                'Chol Sar',
                'Kaoh Thkov',
                'Kampong Os',
                'Peam Chhkaok',
                'Prey Kri',
            ],
            'Kampong Chhnang' => [
                'Phsar Chhnang',
                'Kampong Chhnang',
                "B'er",
                'Khsam',
            ],
            'Kampong Leaeng' => [
                'Chranouk',
                'Dar',
                'Kampong Hau',
                'Phlov Tuk',
                'Pou',
                'Pralay Meas',
                'Samraong Saen',
                'Svay Rumpear',
                'Tra Ngil',
            ],
            'Kampong Tralach' => [
                'Ampil Tuek',
                'Chhuk Sa',
                'Chres',
                'Kampong Tralach',
                'Longveaek',
                'Ou Ruessei',
                'Peani',
                'Saeb',
                'Ta Ches',
                'Thma Edth',
            ],
            "Rolea B'ier" => [
                'Andoung Snay',
                'Banteay Preal',
                'Cheung Kreav',
                'Chrey Bak',
                'Kouk Banteay',
                'Krang Leav',
                'Pongro',
                'Prasnoeb',
                'Prey Mul',
                "Rolea B'ier",
                'Srae Thmei',
                'Svay Chrum',
                'Tuek Hout',
            ],
            'Sameakki Mean Chey' => [
                'Chhean Laeung',
                'Khnar Chhmar',
                'Krang Lvea',
                'Peam',
                'Sedthei',
                'Svay',
                'Svay Chuk',
                'Tbaeng Khpos',
                'Thlok Vien',
            ],
            'Tuek Phos' => [
                'Akphivoadth',
                'Chieb',
                'Chaong Maong',
                'Kbal Tuek',
                'Khlong Popok',
                'Krang Skear',
                'Tang Krasang',
                'Tuol Khpos',
                'Kdol Senchey',
            ],

            // Kampong Speu
            'Borsedth' => [
                'Basedth',
                'Kat Phluk',
                'Nitean',
                'Pheakdei',
                'Pheari Mean Chey',
                'Phong',
                'Pou Angkrang',
                'Pou Chamraeun',
                'Pou Mreal',
                'Svay Chacheb',
                'Tuol Ampil',
                'Tuol Sala',
                'Kak',
                'Svay Rumpear',
                'Preah Khae',
            ],
            'Chbar Mon' => [
                'Chbar Mon',
                'Kandaol Dom',
                'Roka Thum',
                'Sopoar Tep',
                'Svay Kravan',
            ],
            'Kong Pisei' => [
                'Angk Popel',
                'Chongruk',
                'Moha Ruessei',
                'Pechr Muni',
                'Preah Nipean',
                'Prey Nheat',
                'Prey Vihear',
                'Roka Kaoh',
                'Sdok',
                'Snam Krapeu',
                'Srang',
                "Tuek L'ak",
                'Veal',
            ],
            'Aoral' => [
                'Haong Samnam',
                'Reaksmei Sameakki',
                'Trapeang Chour',
                'Sangkae Satob',
                'Ta Sal',
            ],
            'Phnum Sruoch' => [
                'Chambak',
                'Choam Sangkae',
                'Dambouk Rung',
                'Kiri Voan',
                'Krang Dei Vay',
                'Moha Sang',
                'Ou',
                'Prey Rumduol',
                'Prey Kmeng',
                'Tang Samraong',
                'Tang Sya',
                'Traeng Trayueng',
            ],
            'Samraong Tong' => [
                'Roleang Chak',
                'Kahaeng',
                'Khtum Krang',
                'Krang Ampil',
                'Pneay',
                'Roleang Kreul',
                'Samrong Tong',
                'Sambo',
                'Saen Dei',
                'Skuh',
                'Tang Krouch',
                'Thummoda Ar',
                'Trapeang Kong',
                'Tumpoar Meas',
                'Voa Sar',
            ],
            'Thpong' => [
                'Amleang',
                'Monourom',
                'Prambei Mum',
                'Rung Roeang',
                'Toap Mean',
                'Veal Pon',
                'Yea Angk',
            ],
            'Odongk Meae Chey' => [
                'Vaing Chass',
                'Veal Pong',
                'Trach Tong',
                'Preah Srae',
                'Khsem Khsan',
            ],
            'Samakki Muny Chey' => [
                'Chan Saen',
                'Cheung Roas',
                'Chumpu Proeks',
                'Krang Chek',
                'Mean Chey',
                'Prey Krasang',
                'Yutth Sameakki',
                'Damnak Reang',
                'Peang Lvea',
                'Phnum Touch',
            ],

            // Kampot
            'Angkor Chey' => [
                'Angk Phnum Touch',
                'Ankor Chey',
                'Champei',
                'Dambouk Khpos',
                'Dan Koum',
                'Daeum Doung',
                'Mroum',
                'Phnum Kong',
                'Praphnum',
                'Samlanh',
                'Tani',
            ],
            'Banteay Meas' => [
                'Banteay Meas Khang Kaeut',
                'Banteay Meas Khang Lech',
                'Prey Tonle',
                'Samraong Kraom',
                'Samraong Leu',
                'Sdach Kong Khang Cheung',
                'Sdach Kong Khang Lech',
                'Sdach Kong Khang Tboung',
                'Tnoat Chong Srang',
                'Trapeang Sala Khang Kaeut',
                'Trapeang Sala Khang Lech',
                'Tuk Meas Khang Kaeut',
                'Tuk Meas Khang Lech',
                'Voat Angk Khang Cheung',
                'Voat Angk Khang Tboung',
            ],
            'Chhuk' => [
                'Baniev',
                'Takaen',
                'Boeng',
                'Chhuk',
                'Doun Yay',
                'Krang Sbov',
                'Krang Snay',
                'Lbaeuk',
                'Trapeang Phleang',
                'Mean Chey',
                'Neareay',
                'Satv Pong',
                'Trapeang Bei',
                'Tramaeng',
                'Dechou Akphivoadth',
            ],
            'Chum Kiry' => [
                'Chres',
                'Chumpu Voan',
                'Snay Anhchit',
                'Srae Chaeng',
                'Srae Knong',
                'Srae Samraong',
                'Trapeang Reang',
            ],
            'Dong Tong' => [
                'Damnak Sokram',
                'Dang Tong',
                'Khcheay Khang Cheung',
                'Khcheay Khang Tboung',
                'Mean Ritth',
                'Srae Chea Khang Cheung',
                'Srae Chea Khang Tboung',
                'Totung',
                'Angk Romeas',
                "L'ang",
            ],
            'Kampong Tralarch' => [
                'Boeng Sala Khang Cheung',
                'Boeng Sala Khang Tboung',
                'Damnak Kantuot Khang Cheung',
                'Damnak Kantuot Khang Tboung',
                'Kampong Trach Khang Kaeut',
                'Kampong Trach Khang Lech',
                'Prasat Phnom Khyang',
                'Phnom Prasat',
                'Ang Sophy',
                'Preaek Kroes',
                'Ruessei Srok Khang Kaeut',
                'Ruessei Srok Khang Lech',
                'Svay Tong Khang Cheung',
                'Svay Tong Khang Tboung',
            ],
            'Tuek Chhu' => [
                'Boeng Tuk ',
                'Chum Kriel',
                'Kampong Kraeng',
                'Kampong Samraong',
                'Kandaol',
                'Kaoh Touch',
                'Koun Satv',
                'Makprang',
                'Preaek Tnoat',
                'Prey Khmum',
                'Prey Thnang',
                'Stueng Kaev',
                'Thmei',
                'Trapeang Pring',
                'Trapeang Sangkae',
                'Trapeang Thum',
            ],
            'Kampot' => [
                'Kampong Kandal',
                'Krang Ampil',
                'Kampong Bay',
                'Andoung Khmer',
                'Traeuy Kaoh',
            ],
            'Bok Kor' => [
                'Boeng Tok',
                'Koh Toch',
                'Preak Tnout',
            ],

            // Kandal
            'Kandal Stueng' => [
                'Ampov Prey',
                'Anlong Romiet',
                'Barku',
                'Boeng Khyang',
                'Cheung Kaeub',
                'Daeum Rues',
                'Kandaok',
                'Thmei',
                'Kouk Trab',
                'Preah Putth',
                'Preaek Roka',
                'Preaek Slaeng',
                'Roka',
                'Roleang Kaen',
                'Siem Reab',
                'Tbaeng',
                'Trapeang Veaeng',
                'Trea',
            ],
            'Kien Svay' => [
                'Banteay Daek',
                'Chheu Teal',
                'Dei Edth',
                'Kampong Svay',
                'Kokir',
                'Kokir Thum',
                'Phum Thum',
                'Samraong Thum',
            ],
            'Khsach Kandal' => [
                'Bak Dav',
                'Chey Thum',
                'Kampong Chamlang',
                'Kaoh Chouram',
                'Kaoh Oknha Tei',
                'Preah Prasab',
                'Preaek Ampil',
                'Preaek Luong',
                'Preaek Ta Kov	',
                'Preaek Ta Meak',
                'Puk Ruessei',
                'Roka Chonlueng',
                'Sanlung',
                'Sithor',
                'Svay Chrum',
                'Svay Romiet',
                'Ta Aek',
                'Vihear Suork',
            ],
            'Kaoh Thum' => [
                'Kampong Kong',
                'Kaoh Thum Ka',
                'Kaoh Thum Kha',
                'Leuk Daek',
                'Pou Ban',
                'Preaek Thmei',
            ],
            'Leuk Daek' => [
                'Kampong Phnum',
                "K'am Samnar",
                'Khpob Ateav',
                'Peam Reang',
                'Preaek Dach',
                'Preaek Tonloab',
                'Sandar',
            ],
            'Lvea Aem' => [
                'Akreiy Ksatr',
                'Barong',
                'Boeng Krum',
                'Kaoh Kaev',
                'Kaoh Reah',
                'Lvea Sar',
                'Peam Oknha Ong',
                'Phum Thum',
                'Preaek Kmeng',
                'Preaek Rey',
                'Preaek Ruessei',
                'Sambuor',
                'Sarikakaev',
                'Thma Kor',
                'Tuek Khleang',
            ],
            'Mukh Kampul' => [
                'Preak Anhjanh',
                'Preak Dombong',
                'RakaKong Timuy',
                'RakaKong Tipi',
                'Russie Chruy',
                'Sambour Meas',
                'Ampear',
            ],
            'Angk Snuol' => [
                'Bek Chan',
                'Chhok Chher Neang',
                'Damnak Ampil',
                'Krang Mkak',
                'Lum Hach',
                'Mkak',
                'Paek',
                'Pongsang',
                'Prey Proch',
                'Samrong Leu',
                'Toul Peach',
            ],
            'Ponhea Lueu' => [
                'Chhveang',
                'Chrey Loas',
                'Kampong Luong',
                'Kampong Os',
                'Kaoh Chen',
                'Phnum Bat',
                'Ponhea Lueu',
                'Preaek Ta Teaen',
                'Phsar Daek',
                'Tumnob Thum',
                'Vihear Luong',
            ],
            "S'ang" => [
                'Khpob',
                'Kaoh Anlong Chen',
                'Kaoh Khael',
                'Kaoh Khsach Tonlea',
                'Krang Yov',
                'Prasat',
                'Preaek Ambel',
                'Preaek Koy',
                'Roka Khpos',
                "S'ang Phnum",
                'Setbou',
                'Svay Prateal',
                'Svay Rolum',
                'Ta Lon',
                'Traeuy Sla',
                'Tuek Vil',
            ],
            'Ta Khmau' => [
                'Ta Kdol',
                'Prek Ruessey',
                'Doeum Mien',
                'Ta Khmao',
                'Prek Ho',
                'Kampong Samnanh',
                'Svay Rolum',
                'Khosh Anlong Chien',
                'Setbou',
                'Roka Kpos',
            ],

            // Kep
            "Damnak Chang'aeur" => [
                'Angkol',
                'Okrasa',
                'Porng Teok',
            ],
            'Kep' => [
                'Okrasa',
                'Kep',
                'Prey Thom',
            ],

            // Koh Kong
            'Botum Sakor' => [
                'Andoung Tuek',
                'Kandaol',
                'Ta Noun',
                'Thma Sa',
            ],
            'Kiri Sakor' => [
                'Kaoh Sdach',
                'Phnhi Meas',
                'Preaek Khsach',
            ],
            'Kaôh Kŏng' => [
                'Chrouy Pras',
                'Kaoh Kapi',
                'Ta Tai Kraom',
                'Trapeang Rung',
            ],
            'Smach Mean Chey' => [
                'Smach Mean Chey',
                'Dong Tong',
                'Steung Veng',
            ],
            'Mondol Seima' => [
                'Pak Khlang',
                'Peam Krasaob',
                'Tuol Kokir',
            ],
            'Srae Ambel' => [
                'Boeng Preav',
                'Chikha Kraom',
                'Chikha Leu',
                'Chruy Svay',
                'Dong Paeng',
                'Srae Ambel',
            ],
            'Thmo Bang' => [
                'Chi Phat',
                'Pra Lay',
                'Chum Nub',
                'Thma Dunpoa',
                'Russei Chrum',
                'Tatai Vil',
            ],
            'Kampong Seila' => [
                'Chamkar Luong',
                'Kampong Seila',
                'Ou Bak Roteh',
                'Stueng Chhay',
            ],

            // Kratie
            'Chhloung' => [
                'Chhloung',
                'Damrey Phong',
                'Hanchey',
                'Kampong Damrey',
                'Kanh Chor',
                'Khsach Andet',
                'Pong Ra',
                'Preak Saman',
            ],
            'Kratie' => [
                'Ou Russei',
                'Raka Kandal',
                'Kratie',
                'Kra Kor',
                'Koh Trong',
            ],
            'Preaek Prasab' => [
                'Cham Bok',
                'Chroy Banteay',
                'Kampong Kor',
                'Koh Tasuy',
                'Preak Prasab',
                'Russei Keo',
                'Soub',
                'Tamao',
            ],
            'Sambour' => [
                'Kbal Damrey',
                'Koh Khmer',
                'Ou Krieng',
                'Ralos Mean Chey',
                'Kampong Cham',
                'Boeng Chor',
                'Sambour',
                'Sandan',
                'Srae Chis',
                'Vatanak',
            ],
            'Snuol' => [
                'Khsuem',
                'Pir Thnu',
                'Snuol ',
                'Srae Char',
                'Svay Chreah',
                'Kronhoung Saen Chey',
            ],
            'Chet Borei' => [
                'Kan Tut',
                'Thma Andaek',
                'Koh Chraeng',
                'Sambok',
                'Kor Laub',
                'Thmei',
                'Da',
                'Bos Leav',
                'Chongkrong',
                'Thma Krae',
            ],
            "O'Kreang Senchey" => [
                'Kbal Damrey',
                'Ou Kriev',
                'Saen Chey',
                'Ralos Mean Chey',
                'Srae Chis',
            ],

            // Mondulkiri
            'Kaev Seima' => [
                'Chong Phlah',
                'Memang',
                'Srae Chhuk',
                'Srae Khtum',
                'Srae Preah',
            ],
            'Kaoh Nheaek' => [
                'Norng Khilik',
                'Orbuornlue',
                'Rayor',
                'Soksan',
                'Srae huy',
                'Srae Sangkum',
            ],
            'Ou Reang' => [
                'Dak Dum',
                'Senmonorom',
            ],
            'Pech Chreada' => [
                'Krang Tes',
                'Pu Chrey',
                'Srae Ampul',
                'Bu Sra',
            ],
            'Senmonorom' => [
                'Monourom ',
                'Sokh Dom',
                'Spean Mean Chey',
                'Romonea',
            ],

            // Phnom Penh
            'Chamkar Mon' => [
                'Tonle Basak',
                'Tuol Tumpung II',
                'Tuol Tumpung I',
                'Boeng Trobaek',
                'Phsar Daem Thkov',
            ],
            'Daun Penh' => [
                'Srah Chak',
                'Voat Phnum',
                'Phsar Chas',
                'Phsar Kandal Ti Muoy',
                'Phsar Kandal Ti Pir',
                'Chey Chummeah',
                'Chakto Mukh',
                'Phsar Thmei Ti Muoy',
                'Phsar Thmei Ti Pir',
                'Phsar Thmei Ti Bei',
                'Boeng Reang',
            ],
            'Prampi Makara' => [
                'Monourom',
                'Mittpheap',
                'Veal Vong',
                'Ou Russei Mouy',
                'Ou Russei Pir',
                'Ou Russei Bei',
                'Ou Russei Boun',
                'Boeng Pralit',
            ],
            'Toul Kork' => [
                'Phsa Depo I',
                'Phsa Depo II',
                'Phsa Depo III',
                'Boeng Kak I',
                'Boeng Kak II',
                "Tuek L'ak I",
                "Tuek L'ak II",
                "Tuek L'ak III",
                'Phsar Daeumkor',
                'Boeng Salang',
            ],
            'Mean Chey' => [
                'Chak Angrae Leu',
                'Chak Angrae Kraom',
                'Stueng Mean Chey 1',
                'Stueng Mean Chey 2',
                'Stueng Mean Chey 3',
                'Boeng Tumpun 1',
                'Boeng Tumpun 2',
            ],
            'Dangkao' => [
                'Dangkao',
                'Pong Tuek',
                'Prey Veaeng',
                'Prey Sa',
                'Krang Pongro',
                'Prateah Lang',
                'Sak Sampov',
                'Cheung Aek',
                'Kong Noy',
                'Preaek Kampues',
                'Roluos',
                'Spean Thma',
                'Tien',
            ],
            'Russey Keo' => [
                'Svay Pak',
                'Kilomet Prammouy',
                'Russey Keo',
                'Chrang Chamreh I',
                'Chrang Chamreh II',
                'Tuol Sangkae I',
                'Tuol Sangkae II',
            ],
            'Sen Sok' => [
                'Phnom Penh Thmei',
                'Tuek Thla',
                'Khmuonh',
                'Krang Thnong',
                "Ou Baek K'am",
                'Kouk Khleang',
            ],
            'Por Senchey' => [
                'Trapeang Krasang',
                'Samraong Kraom',
                'Chaom Chau 1',
                'Chaom Chau 2',
                'Chaom Chau 3',
                'Kakab 1',
                'Kakab 2',
            ],
            'Chroy Changvar' => [
                'Prek Leap',
                'Prek Ta Sek',
                'Chroy Changvar',
                'Bak Khaeng',
                'Koh Dach',
            ],
            'Prek Pnov' => [
                'Ponhea Pon',
                'Prek Pnov',
                'Samraong',
                'Kouk Roka',
                'Ponsang',
            ],
            'Chbar Ampov' => [
                'Chbar Ampov I',
                'Chbar Ampov II',
                'Nirouth',
                'Prek Pra',
                'Veal Sbov',
                'Prek Aeng',
                'Kbal Koh',
                'Prek Thmei',
            ],
            'Boeng Keng Kang' => [
                'Boeung Keng Kang I',
                'Boeung Keng Kang II',
                'Boeung Keng Kang III',
                'Olympic',
                'Tumnob Tuek',
                'Tuol Svay Prey I',
                'Tuol Svay Prey II',
            ],
            'Kamboul' => [
                'Kamboul',
                'Kantouk',
                'Ovlaok',
                'Snaor',
                'Phleung Chheh Roteh',
                'Boeng Thum',
                'Prateah Lang',
            ],

            // Preah Vihear
            'Preah Vihear city' => [
                'Kampong Pranak',
                'Pal Hal',
            ],
            'Chey Saen' => [
                "S'ang",
                'Tasu',
                'Khyang',
                'Chrach',
                'Thmea',
                'Putrea',
            ],
            'Chhaeb' => [
                'Chhaeb Muoy',
                'Chhaeb Pir',
                'Sangkae Muoy',
                'Sangkae Pir',
                'Mlu Prey Muoy',
                'Mlu Prey Pir',
                'Kampong Sralau Muoy',
                'Kampong Sralau Pir',
            ],
            'Choam Khsant' => [
                'Choam Ksant',
                'Tuek Kraham',
                'Pring Thum',
                'Rumdaoh Srae',
                'Yeang',
                'Kantuot',
                'Sror Aem',
                'Morokot',
            ],
            'Kuleaen' => [
                'Kuleaen Tboung',
                'Kuleaen Cheung',
                'Thmei',
                'Phnum Penh',
                'Phnum Tbaeng Pir',
                'Srayang',
            ],
            'Rovieng' => [
                'Robieb',
                'Reaksmei',
                'Rohas',
                'Rung Roeang',
                'Rik Reay',
                'Ruos Roan',
                'Rotanak',
                'Rieb Roy',
                'Reaksa',
                'Rumdaoh',
                'Romtum',
                'Romoneiy',
            ],
            'Sangkom Thmei' => [
                'Chamraeun',
                "Ro'ang",
                'Phnum Tbaeng Muoy',
                'Sdau',
                'Ronak Ser',
            ],
            'Tbaeng Mean chey' => [
                'Kampong Branak',
                'Chhean Mukh',
                'Pou',
                'Prame',
                'Preah Khleang',
            ],

            // Prey Veng
            'Ba Phnum' => [
                'Boeng Preah',
                'Cheung Phnum',
                'Chheu Kach',
                'Reaks Chey',
                'Roung Damrei',
                'Sdau Kaong',
                'Spueu Ka',
                'Spueu Kha',
                'Theay',
            ],
            'Kamchay Mear' => [
                'Cheach',
                'Doun Koeng',
                'Kranhung',
                'Krabau',
                'Seang Khveang',
                'Smaong Khang Cheung',
                'Smaong Khang Tboung',
                'Trabaek',
            ],
            'Kampong Trabaek' => [
                'Ansaong',
                'Cham',
                'Cheang Daek',
                'Chrey ',
                'Kansoam Ak',
                'Kou Khchak',
                'Kampong Trabaek',
                'Peam Montear',
                'Prasat',
                'Pratheat',
                'Prey Chhor',
                'Prey Poun',
                'Thkov',
            ],
            'Kanhchriech' => [
                'Chong Ampil',
                'Kanhchriech',
                'Kdoeang Reay',
                'Kouk Kong Kaeut',
                'Kouk Kong Lech',
                'Preal',
                'Thma Pun',
                'Tnaot',
            ],
            'Me Sang' => [
                'Angkor Sar',
                'Chres',
                'Chi Phoch',
                'Prey Khnes',
                'Prey Rumdeng',
                'Prey Totueng',
                'Svay Chrum',
                'Trapeang Srae',
            ],
            'Peam Chor' => [
                'Angkor Angk',
                'Kampong Prasat',
                'Kaoh Chek',
                'Kaoh Roka',
                'Kaoh Sampov',
                'Krang Ta Yang',
                'Preaek Krabau',
                'Preaek Sambuor',
                'Ruessei Srok',
                'Svay Phluoh',
            ],
            'Peam Ro' => [
                'Ba Boung',
                'Banlich Brasat',
                'Nak Loeung',
                'Peam Mean Chey',
                'Peam Ro',
                'Preak Khsay Ka',
                'Preak Khsay Kha',
                'Prey Kandieng',
            ],
            'Pea Reang' => [
                'Kampong Popil',
                'Kanhcham',
                'Kampong Prang',
                'Mesar Prachan',
                'Prey Pnov',
                'Prey Sniet',
                'Prey Sralet',
                'Reab',
                'Roka',
            ],
            'Preah Sdach' => [
                'Angkor Reach',
                'Banteay Chakrey',
                'Boeng Doul',
                'Chey Kampok',
                'Kampong Soeng',
                'Kraeng Svay',
                'Lvea',
                'Preah Sdach',
                'Rea Thor',
                'Ramchek',
                'Senareach Ukdom',
            ],
            'Krong Prey Veng' => [
                'Baray',
                'Choeng Touk',
                'Kampong Leav',
                'Takor',
            ],
            'Pur Rieng' => [
                'Pur Rieng',
                'Kampong Russei',
                'Preak Antes',
                'Preak Chrey',
                'Prey Kanlong',
                'Preak Tasor',
            ],
            'Sithor Kandal' => [
                'Ampil Krau',
                'Chrey Khmum',
                'Lve',
                'Pnov Ti Muoy',
                'Pnov Ti Pir',
                'Pnov Ti Bei',
                'Preaek Changkran',
                'Prey Daeum Thnoeng',
                'Prey Tueng',
                'Rumlech',
                'Ruessei Sanh',
            ],
            'Svay Antor' => [
                'Angkor Tret',
                'Chea Khlang',
                'Chrey',
                'Damrei Puon',
                'Me Bon',
                'Pean Roung',
                'Popueus',
                'Prey Khla',
                'Samraong',
                'Svay Antor',
                'Tuek Thla',
            ],

            // Pursat
            'Bakan' => [
                'Boeng Bat Kandaol',
                'Boeng Khnar',
                'Khnar Totueng',
                'Me Tuek',
                'Ou Ta Paong',
                'Rumlech',
                'Snam Preah',
                'Svay Doun',
                'Ta Lou',
                'rapeang Chorng',
            ],
            'Kandieng' => [
                'Anlong Vil',
                'Kandieng',
                'Kanhchor',
                'Reang Til',
                'Srae Sdok',
                'Svay Luong',
                'Sya',
                'Veal',
                'Kaoh Chum',
            ],
            'Krakor' => [
                'Anlong Tnaot',
                'Ansa Chambak',
                'Boeng Kantuot',
                'Chheu Tom',
                'Kampong Luong',
                'Kampong Pou',
                'Kbal Trach',
                'Ou Sandan',
                'Sna Ansa',
                'Svay Sa',
                'Tnaot Chum',
            ],
            'Phnom Kravanh' => [
                'Bak Chenhchien',
                'Leach',
                'Prongil',
                'Rokat',
                'Santreae',
                'Samraong',
            ],
            'Pursat Municipalit' => [
                'Chamraeun Phal',
                'Lolok Sa',
                'Phteah Prey',
                'Prey Nhi',
                'Roleab',
                'Svay At',
                'Banteay Dei',
            ],
            'Veal Veng' => [
                'Anlong Reab',
                'Krapue Pir',
                'Orsom',
                'Bramay',
                'Thmada',
            ],
            'Talo Sen Chey' => [
                'Ta Lou',
                'Pteah Rung',
            ],

            // 
            'Andoung Meas' => [
                'Ma Lik',
                'Nhang',
                'Talao',
            ],
            'Ban Lung' => [
                'Kachanh',
                'Labansiek',
                'Yeak Laom',
                'Boeng Kansaeng',
            ],
            'Bar Kaev' => [
                'Kak',
                'Keh Chong',
                'La Minh',
                'Lung Khung',
                'Saeung',
                'Ting Chak',
            ],
            'Koun Mom' => [
                'Serei Mongkol',
                'Srae Angkrorng',
                'Ta Ang',
                'Teun',
                'Trapeang Chres',
                'Trapeang Kraham',
            ],
            'Lumphat' => [
                'Chey Otdam',
                'Ka Laeng',
                'Lbang Muoy',
                'Lbang Pir',
                'Ba Tang',
                'Seda',
            ],
            'Ou Chum' => [
                'Cha Ung',
                'Pouy',
                'Aekakpheap',
                'Kalai',
                'Ou Chum',
                'Sameakki',
                "L'ak",
            ],
            'Ou Ya Dav' => [
                'Bar Kham',
                'Lum Choar',
                'Pak Nhai',
                'Pa Te',
                'Sesan',
                'Saom Thum',
                'Ya Tung',
            ],
            'Ta Veaeng' => [
                'Ta Veaeng Leu',
                'Ta Veaeng Kraom',
            ],
            'Veun Sai' => [
                'Pong',
                'Hat Pak',
                'Ka Choun',
                'Kaoh Pang',
                'Kaoh Peak',
                'Kok Lak',
                'Pa Kalan',
                'Phnum Kok',
                'Veun Sai',
            ],

            // Siem Reap
            'Angkor Chum' => [
                'Char Chhuk',
                'Don Peaeng',
                'Kouk Doung',
                'Koul',
                'Nokor Pheas',
                'Srae Khvav',
                'Ta Saom',
            ],
            'Angkor Thum' => [
                'Chob Ta Trav',
                'Leang Dai',
                'Peak Snaeng',
                'Svay Chek',
            ],
            'Banteay Srei' => [
                'Khnar Sanday',
                'Khun Ream',
                'Preak Dak',
                'Rumchek',
                'Run Ta EK',
                'Tbaeng',
            ],
            'Chi Kraeng' => [
                'Anlong Samnar',
                'Chi Kraeng',
                'Kampong Kdei',
                'Khvav',
                'Kouk Thlok Kraom',
                'Kouk Thlok Leu',
                'Lveaeng Ruessei',
                'Pongro Kraom',
                'Pongro Leu',
                'Ruessei Lok',
                'Sangvaeuy',
                'Spean Tnaot',
            ],
            'Kralanh' => [
                'Chonloas Dai',
                'Kampong Thkov',
                'Kralanh',
                'Krouch Kor',
                'Roung Kou',
                'Sambuor',
                'Saen Sokh',
                'Snuol',
                'Sranal',
                'Ta an',
            ],
            'Puok' => [
                'Sasar Sdam',
                'Doun Kaev',
                'Kdei Run',
                'Kaev Poar',
                'Khnat',
                'Lvea',
                'Mukh Paen',
                'Pou Treay',
                'Puok',
                'Prey Chruk',
                'Reul',
                'Samraong Yea',
                'Trei Nhoar',
                'Yeang',
            ],
            'Prasat Bakong' => [
                'Ampil',
                'Bakong',
                'Ballangk',
                'Kampong Phluk',
                'Kantreang',
                'Kandaek',
                'Mean Chey',
                'Roluos',
                'Trapeang Thum',
            ],
            'Siem Reab' => [
                'Sla Kram',
                'Svay Dankum',
                'Kok Chak',
                'Sala Kamreuk',
                'Nokor Thum',
                'Chreav',
                'Chong Khnies',
                'Sambuor ',
                'Siem Reab',
                'Srangae ',
                'Krabei Riel',
                'Tuek Vil',
            ],
            'Soutr Nikom' => [
                'Chan Sar',
                'Dam Daek',
                'Dan Run',
                'Kampong Khleang',
                'Kien Sangkae',
                'Khchas',
                'Khnar Pou',
                'Popel',
                'Samraong',
                'Ta Yaek',
            ],
            'Srei Snam' => [
                'Chrouy Neang Nguon',
                'Klang Hay',
                'Tram Sasar',
                'Moung',
                'Prei',
                'Slaeng Spean',
            ],
            'Svay Leu' => [
                'Boeng Mealea',
                'Kantuot',
                'Khnang Phnum',
                'Svay Leu',
                'Ta Siem',
            ],
            'Varin' => [
                'Prasat',
                'Lvea Krang',
                'Srae Nouy',
                'Svay sa',
                'Varin',
            ],

            // Preah Sihanouk
            'Preah Sihanouk' => [
                'Sangkat Ti Mouy',
                'Sangkat Ti Pir',
                'Sangkat Ti Bei',
                'Sangkat Ti Boun',
                'Sangkat Ti Pram',
                'Sangkat Ti Pramouy',
            ],
            'Prey Nop' => [
                'Andoung Thma',
                'Boeng Ta Prum',
                'Bet Trang',
                'Cheung Kou',
                'Ou Chrov',
                'Ou Oknha Heng',
                'Prey Nob',
                'Ream',
                'Sameakki',
                'Samrong',
                "Tuek L'ak",
                'Tuek Thla',
                'Tuol Totueng',
                'Veal Renh',
                'Ta Ney',
            ],
            'Stung Hao' => [
                'Kampenh',
                'Ou Treh',
                'Tumnob Rolok',
                'Kaev Phos',
            ],
            'Kampong Seila' => [
                'Chamkar Luong',
                'Kampong Seila',
                'Ou Bak Roteh',
                'Stueng Chhay',
            ],
            'Koh Rong' => [
                'Kaoh Rung',
                'Kaoh Rung Sonlem',
            ],
            'Kampong Soam' => [
                'Ream',
                'Bet Trang',
                'Ou Oknha Heng',
                'Boeng Ta Prum',
                'Ou Chrov',
            ],

            // Stung Treng
            'Sesan' => [
                'Kampun',
                'Kbal Romeas',
                'Plok',
                'Sam Khouy',
                'Sdav',
                'Sraekor',
                'Talat',
            ],
            'Siem Bouk' => [
                'Koh Preah',
                'Koh Sampov',
                'Koh Sralay',
                'Ou Mreah',
                'Ou Ruessei Kandal',
                'Siem Bouk',
                'Srae Krasang',
            ],
            'Siem Pang' => [
                'Prek Meas',
                'Sekong ',
                'Santiphap ',
                'Srae Sambuor',
                'Thma Keo',
            ],
            'Stueng Traeng' => [
                'Stung Treng',
                'Srah Russei',
                'Preah Bat',
                'Samakki',
            ],
            'Thala Barivat' => [
                'Anlong Phe',
                'Chamkar Leu',
                'Kang Cham',
                'Anlong Chrey',
                'Ou Rey',
                'Samáng ',
                'Srae Ruessei',
                'Thala Borivat',
            ],
            "Borey O'svay sen Chey" => [
                "O'Svay",
                'koh Sneng',
                'Preah Romkel',
            ],

            // Svay Rieng
            'Chanthrea' => [
                'Chantrea',
                'Chres',
                'Me Sar Thngak',
                'Prey Kokir',
                'Samraong',
                'Tuol Sdei',
            ],
            'Kampong Rou' => [
                'Banteay Krang',
                'Nhor',
                'Khsaetr',
                'Preah Ponlea',
                'Prey Thum',
                'Reach Montir',
                'Samlei',
                'Samyaong',
                'Svay Ta Yean',
                'Thmei',
                'Tnaot',
            ],
            'Romdoul' => [
                'Bos Mon',
                'Thmea ',
                'Kampong Chak',
                'Chrung Popel',
                'Kampong Ampil',
                'Meun Chey',
                'Pong Tuek',
                'Sangkae',
                'Svay Chek',
                'Thna Thnong',
            ],
            'Romeas Haek' => [
                'Ampil',
                'Andoung Pou',
                'Andoung Trabaek',
                'Angk Prasrae',
                'Chantrei',
                'Chrey Thum',
                'Doung',
                'Kampong Trach',
                'Kokir',
                'Krasang',
                'Mukh Da',
                'Mream',
                'Sambuor',
                'Sambatt Mean Chey',
                'Trapeang Sdau',
                'Tras',
            ],
            'Svay Chrom' => [
                'Angk Ta Sou',
                'Basak',
                'Chambak',
                'Kampong Chamlang',
                'Ta Suos',
                'Chheu Teal',
                'Doun Sa',
                'Kouk Pring',
                'Kraol Kou',
                'Kruos',
                'Pouthi Reach',
                'Svay Angk',
                'Svay Chrum',
                'Svay Thum',
                'Svay Yea',
                'Thlok',
            ],
            'Svay Rieng' => [
                'Svay Rieng',
                'Prey Chhlak',
                'Koy Trabaek',
                'Pou Ta Hao',
                'Chek',
                'Svay Toea',
                'Sangkhoar',
            ],
            'Svay Theab' => [
                'Koki Saom',
                'Kandieng Reay',
                'Monourom',
                'Popeaet',
                'Prey Ta Ei',
                'Prasoutr',
                'Romeang Thkaol',
                'Sambuor',
                'Svay Rumpear',
            ],
            'Bavet' => [
                'Bati',
                'Bavet',
                'Chrak Mtes',
                'Prasat',
                'Prey Angkunh',
            ],

            // Ta Keo
            'Angkor Boery' => [
                'Angkor Borei',
                'Ba Srae',
                'Kouk Thlok',
                'Ponley ',
                'Preaek Phtoul',
                'Prey Phkoam',
            ],
            'Ba Ti' => [
                'Chambak',
                'Champei',
                'Doung',
                'Kandoeng',
                'Komar Reachea',
                'Krang Leav',
                'Krang thnong',
                'Lumpong',
                'Pea Ream',
                'Pot Sar',
                'Souphi',
                'Tang Doung',
                'Tnaot',
                'Trapeang Krasang',
                'Trapeang Sab',
            ],
            'Boery Chulsa' => [
                'Bourei Cholsar',
                'Chey Chouk',
                'Doung Khpos',
                'Kampong Krasang',
                'Kouk Pou',
            ],
            'Kiry Vong' => [
                'Angk Prasat',
                'Preah Bat Choan Chum',
                'Kamnob',
                'Kampaeng',
                'Kiri Chong Kaoh',
                'Kouk Prech',
                'Phnum Den',
                'Prey Ampok',
                'Prey Rumdeng',
                'Ream Andaeuk',
                'Saom',
                'Ta O',
            ],
            'Koh Orndet' => [
                'Krapum Chhuk',
                'Pech Sar',
                'Prey Khla',
                'Prey Yuthka',
                'Romenh',
                'Thlea Prachum',
            ],
            'Prey Kabas' => [
                'Angkanh ',
                'Ban Kam',
                'Champa',
                'Char',
                'Kampeaeng',
                'Kampong Reab',
                'Kdanh',
                'Pou Rumchak',
                'Prey Kabbas',
                'Prey Lvea',
                'Prey Phdau',
                'Snao',
                'Tang Yab',
            ],
            'Samrong' => [
                'Boeng Tranh Khang Cheung',
                'Boeng Tranh Khang Tboung',
                'Cheung Kuon',
                'Chumreah Pen',
                'Khvav',
                'Lumchang',
                'Rovieng',
                'Samraong',
                'Soeng',
                'Sla',
                'Trea',
            ],
            'Dun Keo' => [
                'Baray',
                'Roka Knong',
                'Roka Krau',
            ],
            'Tram Kork' => [
                'Lai Bo',
                'Angk Ta Saom',
                'Cheang Tong',
                'Kos',
                'Lai Bo',
                'Nhaeng Nhoeng',
                'Ou Saray',
                'Uddom Soriya',
                'Popel',
                'Samraong',
                'Srae Ronoang',
                'Ta Phem',
                'Tram Kak',
                'Trapeang Thum Khang Cheung',
                'Trapeang Thum Khang Tboung',
                'Trapeang Kragnoung',
            ],

            'Traeng' => [
                'Angkanh',
                'Angk Khnor',
                'Chi Khma',
                'Khvav	',
                'Prambei Mum',
                'Angk Kev',
                'Prey Sloek',
                'Roneam',
                'Sambuor',
                'Sanlong',
                'Smaong',
                'Srongae',
                'Thlok',
                'Trolach',
            ],

            // Oddar Meanchey
            'Anlong Veng' => [
                'Anlong Veaeng',
                'Trapeang Tav',
                'Trapeang Prei',
                'Thlat ',
                'Lumtong ',
            ],
            'Banteay Ampil' => [
                'Ampil ',
                'Beng ',
                'Kouk Khpos',
                'Kouk Mon',
            ],
            'Chong Kal' => [
                'Cheung Tien',
                'Chong Kal',
                'Krasang ',
                'Pongro ',
            ],
            'Samraong' => [
                'Samraong',
                'Bansay Reak',
                'Kon Kriel',
                'Bos Sbov',
                'Ou Smach',
            ],
            'Trapeang Prasat' => [
                'Bak Anloung',
                "Ph'av",
                'Ou Svay',
                'Preah Pralay',
                'Tumnob Dach',
                'Trapeang Prasat',
            ],

            // Pailin
            'Pailin' => [
                'Pailin ',
                'Ou Ta Vau',
                'Tuol Lvea',
                'Bar Yakha',
            ],
            'Salakrao' => [
                'Sala Krao',
                'Stung Trang',
                'Stung Kach',
                'Ou Andoung',
            ],


            // Tboung Khmum
            'Suong' => [
                'Suong',
                'Vihear Luong'
            ],
            'Dambae' => [
                'Chong Cheach',
                'Dambae ',
                'Kouk Srok',
                'Neang Teut',
                'Seda',
                'Trapeang Pring',
                'Tuek Chrov',
            ],
            'Krouch Chhmar' => [
                'Chhuk',
                'Chumnik',
                'Kampong Treas',
                'Kaoh Pir',
                'Krouch Chhmar',
                'Peus Muoy',
                'Peus Pir',
                'Preaek A Chi',
                'Roka Khnor',
                'Svay Khleang',
                'Trea',
                'Tuol Snuol',
            ],
            'Memot' => [
                'Chan Mul',
                'Choam',
                'Choam Kravien',
                'Choam Ta Mau',
                'Dar',
                'Kampoan',
                'Kokir',
                'Memong',
                'Memot',
                'Rumchek',
                'Rung',
                'Tonlung',
                'Tramung',
                'Triek',
            ],
            'Ou Reang Ov' => [
                'Ampil Ta Pok',
                'Chak',
                'Damril',
                'Kong',
                'Mien',
                'Preah Theat',
                'Tuol Souphi',
            ],
            'Ponhea Kraek' => [
                'Dountei',
                'Kak',
                'Kandaol Chrum',
                'Kaong Kang',
                'Kraek',
                'Popel',
                'Trapeang Phlong',
                'Veal Mlu',
            ],
            'Tboung Khmum' => [
                'Kor',
                'Chub',
                'Thma Pech',
                'Tonle Bet',
                'Mong Riev',
                'Anhchaeum',
                'Boeng Pruol',
                'Chikor',
                'Chirou I',
                'Chirou II',
                'Lngieng',
                'Peam Chileang',
                'Roka Po Pram',
                'Sralab',
            ],
        ];

        foreach ($data as $districtName => $communes) {
            $district = District::where('name', $districtName)->first();

            if ($district) {
                foreach ($communes as $communeName) {
                    $exists = \App\Models\Commune::where('district_id', $district->id)
                        ->where('name', $communeName)
                        ->exists();

                    if (!$exists) {
                        Commune::create([
                            'district_id' => $district->id,
                            'name' => $communeName,
                        ]);
                    }
                }
            }
        }
    }
}
