<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Province;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            'Banteay Meanchey' => [
                'Mongkol Borey',
                'Phnom Srok',
                'Preah Neth Preah',
                'Ou Chrov',
                'Serei Saophoan',
                'Thma Puok',
                'Svay Chek',
                'Malai',
                'Poipet',
            ],
            'Battambang' => [
                'Banan',
                'Thma Koul',
                'Bat Dambang',
                'Bavel',
                'Aek Phnum',
                'Moung Ruessei',
                'Rotanak Mondol',
                'Sangkae',
                'Samlout',
                'Sampov Lun',
                'Phnum Proek',
                'Kamrieng',
                'Koas Krala',
                'Rukhakiri',
            ],
            'Kampong Cham' => [
                'Batheay',
                'Chamkar Leu',
                'Cheung Prey',
                'Kampong Cham',
                'Kampong Siem',
                'Kang Meas',
                'Kaoh Soutin',
                'Prey Chhor',
                'Srey Santhor',
                'Stueng Trang',
            ],
            'Kampong Chhnang' => [
                'Baribour',
                'Chol Kiri',
                'Kampong Chhnang',
                'Kampong Leaeng',
                'Kampong Tralach',
                "Rolea B'ier",
                'Sameakki Mean Chey',
                'Tuek Phos',
            ],
            'Kampong Speu' => [
                'Borsedth',
                'Chbar Mon',
                'Kong Pisei',
                'Aoral',
                'Phnum Sruoch',
                'Samraong Tong',
                'Thpong',
                'Odongk Meae Chey',
                'Samakki Muny Chey',
            ],
            'Kampong Thom' => [
                'Baray',
                'Kampong Svay',
                'Stueng Saen',
                'Prasat Balang',
                'Prasat Sambour',
                'Sandan',
                'Santuk',
                'Stoung',
                'Taing Kok',
            ],
            'Kampot' => [
                'Angkor Chey',
                'Banteay Meas',
                'Chhuk',
                'Chum Kiry',
                'Dong Tong',
                'Kampong Tralarch',
                'Tuek Chhu',
                'Kampot',
                'Bok Kor',
            ],
            'Kandal' => [
                'Kandal Stueng',
                'Kien Svay',
                'Khsach Kandal',
                'Kaoh Thum',
                'Leuk Daek',
                'Lvea Aem',
                'Mukh Kampul',
                'Angk Snuol',
                'Ponhea Lueu',
                "S'ang",
                'Ta Khmau',
            ],
            'Kep' => [
                "Damnak Chang'aeur",
                'Kep',
            ],
            'Koh Kong' => [
                'Botum Sakor',
                'Kiri Sakor',
                'Kaôh Kŏng',
                'Smach Mean Chey',
                'Mondol Seima',
                'Srae Ambel',
                'Thmo Bang',
            ],
            'Kratie' => [
                'Chhloung',
                'Kratie',
                'Preaek Prasab',
                'Sambour',
                'Snuol',
                'Chet Borei',
                "O'Kreang Senchey",
            ],
            'Mondulkiri' => [
                'Kaev Seima',
                'Kaoh Nheaek',
                'Ou Reang',
                'Pech Chreada',
                'Senmonorom',
            ],
            'Phnom Penh' => [
                'Chamkar Mon',
                'Daun Penh',
                'Prampi Makara',
                'Toul Kork',
                'Mean Chey',
                'Dangkao',
                'Russey Keo',
                'Sen Sok',
                'Por Senchey',
                'Chroy Changvar',
                'Prek Pnov',
                'Chbar Ampov',
                'Boeng Keng Kang',
                'Kamboul'
            ],
            'Preah Vihear' => [
                'Preah Vihear city',
                'Chey Saen',
                'Chhaeb',
                'Choam Khsant',
                'Kuleaen',
                'Rovieng',
                'Sangkom Thmei',
                'Tbaeng Mean chey',
            ],
            'Prey Veng' => [
                'Ba Phnum',
                'Kamchay Mear',
                'Kampong Trabaek',
                'Kanhchriech ',
                'Me Sang',
                'Peam Chor',
                'Peam Ro',
                'Pea Reang',
                'Preah Sdach',
                'Krong Prey Veng',
                'Pur Rieng',
                'Sithor Kandal',
                'Svay Antor',
            ],
            'Pursat' => [
                'Bakan',
                'Kandieng',
                'Krakor',
                'Phnom Kravanh',
                'Pursat Municipality',
                'Veal Veng',
                'Talo Sen Chey',
            ],
            'Ratanakiri' => [
                'Andoung Meas',
                'Ban Lung',
                'Bar Kaev',
                'Koun Mom',
                'Lumphat',
                'Ou Chum',
                'Ou Ya Dav',
                'Ta Veaeng',
                'Veun Sai',
            ],
            'Siem Reap' => [
                'Angkor Chum',
                'Angkor Thum',
                'Banteay Srei',
                'Chi Kraeng',
                'Kralanh',
                'Puok',
                'Prasat Bakong',
                'Siem Reab',
                'Soutr Nikom',
                'Srei Snam',
                'Svay Leu',
                'Varin',
            ],
            'Preah Sihanouk' => [
                'Preah Sihanouk',
                'Prey Nop',
                'Stung Hao',
                'Kampong Seila',
                'Koh Rong',
                'Kampong Soam',
            ],
            'Stung Treng' => [
                'Sesan',
                'Siem Bouk',
                'Siem Pang',
                'Stueng Traeng',
                'Thala Barivat',
                "Borey O'svay sen Chey",
            ],
            'Svay Rieng' => [
                'Chanthrea ',
                'Kampong Rou',
                'Romdoul ',
                'Romeas Haek',
                'Svay Chrom',
                'Svay Rieng',
                'Svay Theab',
                'Bavet ',
            ],
            'Takeo' => [
                'Angkor Boery',
                'Ba Ti',
                'Boery Chulsa',
                'Kiry Vong',
                'Koh Orndet',
                'Prey Kabas',
                'Samrong',
                'Dun Keo',
                'Tram Kork',
                'Traeng',
            ],
            'Oddar Meanchey' => [
                'Anlong Veng',
                'Banteay Ampil',
                'Chong Kal',
                'Samraong',
                'Trapeang Prasat',
            ],
            'Pailin' => [
                'Pailin',
                'Salakrao',
            ],
            'Tboung Khmum' => [
                'Suong',
                'Dambae',
                'Krouch Chhmar',
                'Memot',
                'Ou Reang Ov',
                'Ponhea Kraek',
                'Tboung Khmum',
            ],
        ];
        foreach ($data as $provinceName => $districts) {
            $province = Province::where('name', $provinceName)->first();
            if ($province) {
                foreach ($districts as $districtName) {
                    District::create([
                        'province_id' => $province->id,
                        'name' => $districtName,
                    ]);
                }
            }
        }
    } 
}
